### PR TITLE
add cosmetics to fix build error in README example

### PR DESCRIPTION
**Pull request by nerdoc**

### CODE REVIEW

**Comment by rixo** [comment]
Thanks. 

Those syntax errors are kind of implying that you shouldn't use all of these options together, and that this config is not for copy-paste...

Maybe this should be explicitly mentioned?

Maybe also we should add some basic config intended for copy pasting? (Since this "example" is more of a list of available options than really an example.)

What do you think?

**Comment by nerdoc** [comment]
Oh, definitely, this is needed badly, IMHO. Generally, there are plenty of "examples" all over the web, but they hardly work "batteries included" just by checking them out and running them. I'm evaluating Svelte for a project (more below), coming from Vuejs.

But some example config/code would be a game changer here.

My own requirements are a bit more tricky. I need Django as server, and would like to have Svelte including HMR as client, AND am developing a plugin framework for Django where each app provides frontend plugins as well.
And, as always, I'm embarrassed that noone ever thought about that before. ;-)

**Comment by nerdoc** [comment]
> Maybe also we should add some basic config intended for copy pasting? (Since this "example" is more of a list of available options than really an example.)
And to answer this directly: yes. I think the best way of coding is to have sane defaults, that can be tweaked if wanted, like parcel does it. In the way 80% use it, **no** config needed. So here, at least a copy'n'paste config would be really cool.

**Comment by rixo** [comment]
TBH this plugin is kinda end-of-life. The HMR capacity will probably be integrated into the official Rollup plugin sometime in the near future, but I now seriously doubt Rollup HMR itself will ever really be a thing.

If you're interested in sane defaults, and really fast HMR (which this plugin won't give you, because it's limited by Rollup's own rebuild time, that is not great), you should check Snowpack (that gets special attention from many Svelte contributors, because it will be used by Svelte Kit), or [Svite](https://github.com/dominikg/svite), that might still be a little bit more "finished" at this point.

I have little doubt these no-bundler approaches are superseding the traditional "bundle while dev" approach short term, given the huge advantages they offer during dev, and they still produce almost identical prod bundles using traditional tools.

> I need Django as server, and would like to have Svelte including HMR as client

You'll probably have to make the dev server (that serves the frontend and take care of compiling Svelte + HMR) proxy to your Django API server.

> AND am developing a plugin framework for Django where each app provides frontend plugins as well

If your frontend plugins are Svelte too and you want to compile them independently, you're up for a bit of a challenge. This [SO answer](https://stackoverflow.com/a/65522522/1387519) might help. With the approach underlined there, that is compiling the plugins with Rollup, you'd be able to consume your independent plugins whatever the dev server you're using to dev your main app.

> And, as always, I'm embarrassed that noone ever thought about that before. ;-)

If I understand you well, not sure that's really the case ;p

Regarding this PR, I'm not sure I'm very comfortable with just fixing the "syntax errors". If you're interested in adding some details and maybe a sane default example, I'll be happy to take this in. Otherwise, like I said, this plugin is probably on its way to be integrated into the official one, so I'll be focusing my own efforts in this other direction (and more promising dev server alternatives).

**Comment by frederikhors** [comment]
@rixo do you know about Svelte Kit ETA?

**Comment by rixo** [comment]
@frederikhors No idea. I expect first half of 2021, probably 1st quarter, but that's wild guesswork from me. That being said, Snowpack and Svite already cover a lot of ground for many kind of projects. The killer proposition of Kit (like Sapper, like Routify) is the SSR / PWA aspects, that are not always the target. Especially with Svelte, that can credibly be used as some kind of supercharged jQuery alternative in many context (whereas including React runtime for just little widgets in an otherwise non-React app would be dull).

**Comment by nerdoc** [comment]
@rixo Thank you very much for this great explanation, and yes, in this case something like Snowpack/svite would be much better - so just cancel this PR - this doesn't make sense then.
Regarding the plugin system: In the first place I didn't want to use precompiled Js - in my Vue version, I just made a Django management command that "linked" the found and enabled plugins into a central file by adding imports to it - this file was autogenerated by my management command. That may be a bit clumsy, but I am no professional dev, and just starting with Js - 
Maybe the best approach would be anyway: like you said, using svelte as frontend, snowpack etc. for development, and either linking the plugins in place during the dev cycle - which makes "hot" plugin installs impossible - or going down the hard road and trying the prelinked rollup thing.
But as Django lacks plugins altogether (and I had to write a complete plugin system) - it even is not able to install apps while running - the server has to be restarted - there could be a compile step included as well in that case (BUT would require a dev env on the production server - not good.)

Thank you VERY much for your input. So I'll close that PR here.

**Pull request closed without merging**
